server:
  port:8090
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
             - Path=/authentication-service/**
          filters:
              - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}

        - id: cart-service
          uri: http://localhost:8082
          predicates:
            - Path=/cart-service/**
          filters:
            - RewritePath=/cart-service(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: http://localhost:8083
          predicates:
            - Path=/chat-service/**
          filters:
              - RewritePath=/chat-service(?<segment>/?.*), $\{segment}

        -  id: config-server
           uri: http://localhost:8084
           predicates:
            - Path=/config-server/**
           filters:
            - RewritePath=/config-server(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8085
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/config-server(?<segment>/?.*), $\{segment}

        - id: order-service
          uri: http://localhost:8087
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:8088
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}

        - id: product-service
          uri: http://localhost:8089
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service(?<segment>/?.*), $\{segment}

        - id: slot-service
          uri: http://localhost:8090
          predicates:
            - Path=/slot-service/**
          filters:
            - RewritePath=/slot-service(?<segment>/?.*), $\{segment}

        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
